# This is a config for E2B sandbox template.
# You can use template ID (luia4lwboze5dwrtfzg3) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("luia4lwboze5dwrtfzg3") # Sync sandbox
# sandbox = await AsyncSandbox.create("luia4lwboze5dwrtfzg3") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('luia4lwboze5dwrtfzg3')

team_id = "3aac1eca-21af-4966-9954-1e35b63306e3"
start_cmd = "npm run dev"
dockerfile = "e2b.Dockerfile"
template_id = "luia4lwboze5dwrtfzg3"
