# This is a config for E2B sandbox template.
# You can use template ID (bctos89z148zr6a4zmp4) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("bctos89z148zr6a4zmp4") # Sync sandbox
# sandbox = await AsyncSandbox.create("bctos89z148zr6a4zmp4") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('bctos89z148zr6a4zmp4')

team_id = "3aac1eca-21af-4966-9954-1e35b63306e3"
start_cmd = "/root/.jupyter/start-up.sh"
dockerfile = "e2b.Dockerfile"
template_id = "bctos89z148zr6a4zmp4"
